# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(blank=True, choices=[(b'N', b'Nikon'), (b'C', b'Canon'), (b'K', b'Kodak')], max_length=5, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.CharField(blank=True, default=b'', max_length=1000, null=True)),
                ('website', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('hireable', models.BooleanField(default=True)),
                ('travel_radius', models.IntegerField(blank=True, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('photography_type', models.CharField(blank=True, choices=[(b'LS', b'landscape'), (b'PT', b'portrait'), (b'NA', b'nature'), (b'AS', b'astronomy')], max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
