# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(blank=True, choices=[('N', 'Nikon'), ('C', 'Canon'), ('K', 'Kodak')], max_length=5)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('bio', models.CharField(blank=True, default='', max_length=1000)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('hireable', models.BooleanField(default=True)),
                ('travel_radius', models.IntegerField(blank=True)),
                ('phone', models.IntegerField(blank=True)),
                ('photography_type', models.CharField(blank=True, choices=[('LS', 'landscape'), ('PT', 'portrait'), ('NA', 'nature'), ('AS', 'astronomy')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
