# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imager_profile', '0002_auto_20170120_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_uploaded', models.DateField(blank=True, null=True)),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('published', models.CharField(choices=[('PR', 'private'), ('SH', 'shared'), ('PU', 'public')], default='PU', max_length=255)),
                ('cover', models.ImageField(upload_to='photos')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='imager_profile.ImagerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_uploaded', models.DateField(blank=True, null=True)),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('published', models.CharField(choices=[('PR', 'private'), ('SH', 'shared'), ('PU', 'public')], default='PU', max_length=255)),
                ('image', models.ImageField(upload_to='photos')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_album', to='imager_images.Albums')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographed_by', to='imager_profile.ImagerProfile')),
            ],
        ),
    ]
