# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='cover',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='published',
            field=models.CharField(choices=[('PR', 'private'), ('SH', 'shared'), ('PU', 'public')], default='PU', max_length=255),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='published',
            field=models.CharField(choices=[('PR', 'private'), ('SH', 'shared'), ('PU', 'public')], default='PU', max_length=255),
        ),
    ]
