# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20170125_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='date_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='albums',
            name='date_published',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='albums',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='date_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='date_published',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
