# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 18:23
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('imager_images', '0003_auto_20170127_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
